### ISSUE TITLE
LavaVu not working[BUG]

### ISSUE THREAD

**Issue by mustaeenqazi** [Loop3D/LoopStructural#68] opened 2021-06-15 16:02 UTC
AttributeError: 'LavaVuModelViewer' object has no attribute 'lv'

The Class 'LavaVuModelViewer' does have the attribute 'lv' as seen in the file 'model_visualization.py' Line 62. "self.lv = lavavu.Viewer(**kwargs)" 

The error occurs Even though i have installed the Lavavu library using Pip. 

Secondly: on running the third example following error shows up:

AttributeError: 'LavaVuModelViewer' object has no attribute 'bounding_box'
it seems some problem in the 'LavaVuModelViewer' class

**Expected behavior**
import the 'lavavumodelviewer' object and import the lavavu library in this class. And Plot a surface from the data
![lavavu](https://user-images.githubusercontent.com/66418760/122086164-bb728380-ce03-11eb-8f46-dc65262ce208.png)

**Screenshots**

 - OS: windows
 -  - Python environment [anaconda, python 3.7.1]
 -

**Additional context**

**Comment by lachlangrose** [comment] 2021-06-15 23:15
Hi,

I think the error is occurring because you have not installed lavavu, lavavu isn't installed by default for license reasons. I'm not sure why this error occurs, it should print the error message and stop. I'll look into that.

You should be able to get somewhere if you run `pip install lavavu`. Let me know if that works.

Good luck

**Comment by lachlangrose** [comment] 2021-06-15 23:19
Actually just look at the code, its doing what it should. I have changed it to raise an exception when lavavu isn't installed.

**Comment by mustaeenqazi** [comment] 2021-06-15 23:37
Hello

Thank you. As i mentioned in above The error occurs Even though i have installed the Lavavu. Yes it should work even with the exception but somehow its not importing the lavavu library. 
secondly when i run the third example  from the given exampleson the website i get the following error:
AttributeError: 'LavaVuModelViewer' object has no attribute 'bounding_box' 

cheers,

**Comment by lachlangrose** [comment] 2021-06-15 23:41
Does `import lavavu` work? 

The next error is most likely related because not importing lavavu means the constructor for the viewer isn't run

**Comment by lachlangrose** [comment] 2021-06-16 20:49
Can you run a separate python file import lavavu and tell me if that
produces an error.

**Comment by mustaeenqazi** [comment] 2021-06-18 18:03
Hi ,
Yes when i run a python file with "import lavavu" it works fine. Anyways i tried installing it on python 3.7.7 and somehow it worked. But still cannot run it on the 3.7.1.

**Comment by lachlangrose** [comment] 2021-06-18 22:55
Hi,

The error sounds strange, could you upload your anaconda environment yml
and tell me what operating system you are using? I'll try to recreate the
error.

Thanks

**Comment by mustaeenqazi** [comment] 2021-06-21 12:02
Hi, 
Yes i have created the yml file but somehow itcannot be uploaded here.
Cheers,

**Comment by lachlangrose** [comment] 2021-06-21 12:20
Can you copy and paste the contents in here? Just use the code tags

**Comment by mustaeenqazi** [comment] 2021-06-21 12:24
name: LoopStructural
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2021.5.25=haa95532_1
  - certifi=2021.5.30=py37haa95532_0
  - intel-openmp=2021.2.0=haa95532_616
  - mkl=2021.2.0=haa95532_296
  - mkl-service=2.3.0=py37h2bbff1b_1
  - mkl_fft=1.3.0=py37h277e83a_2
  - mkl_random=1.2.1=py37hf11a4ad_2
  - numpy=1.20.2=py37ha4e8547_0
  - numpy-base=1.20.2=py37hc2deb75_0
  - openssl=1.1.1k=h2bbff1b_0
  - pip=21.1.2=py37haa95532_0
  - python=3.7.10=h6244533_0
  - setuptools=52.0.0=py37haa95532_0
  - six=1.15.0=pyhd3eb1b0_0
  - sqlite=3.35.4=h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.36.2=pyhd3eb1b0_0
  - wincertstore=0.2=py37_0
  - pip:
    - aiohttp==3.7.4.post0
    - alabaster==0.7.12
    - anyio==3.1.0
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - async-timeout==3.0.1
    - attrs==21.2.0
    - babel==2.9.1
    - bleach==3.3.0
    - cffi==1.14.5
    - chardet==4.0.0
    - colorama==0.4.4
    - cycler==0.10.0
    - decorator==4.4.2
    - defusedxml==0.7.1
    - docutils==0.17.1
    - entrypoints==0.3
    - idna==2.10
    - imageio==2.9.0
    - imagesize==1.2.0
    - importlib-metadata==4.5.0
    - ipython-genutils==0.2.0
    - jinja2==3.0.1
    - joblib==1.0.1
    - jsonschema==3.2.0
    - jupyter-client==6.1.12
    - jupyter-core==4.7.1
    - jupyter-server==1.8.0
    - jupyter-server-proxy==3.0.2
    - jupyterlab-pygments==0.1.2
    - kiwisolver==1.3.1
    - lavavu==1.8.12
    - loopstructural==1.0.91
    - markupsafe==2.0.1
    - matplotlib==3.4.2
    - mistune==0.8.4
    - mplstereonet==0.5
    - multidict==5.1.0
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - networkx==2.5.1
    - packaging==20.9
    - pandas==1.2.4
    - pandocfilters==1.4.3
    - pillow==8.2.0
    - prometheus-client==0.11.0
    - pycparser==2.20
    - pygments==2.9.0
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pytz==2021.1
    - pywavelets==1.1.1
    - pywin32==301
    - pywinpty==1.1.2
    - pyzmq==22.1.0
    - requests==2.25.1
    - scikit-image==0.18.1
    - scikit-learn==0.24.2
    - scipy==1.6.3
    - send2trash==1.5.0
    - simpervisor==0.4
    - sniffio==1.2.0
    - snowballstemmer==2.1.0
    - sphinx==4.0.2
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - terminado==0.10.1
    - testpath==0.5.0
    - threadpoolctl==2.1.0
    - tifffile==2021.6.6
    - tornado==6.1
    - tqdm==4.61.1
    - traitlets==5.0.5
    - typing-extensions==3.10.0.0
    - urllib3==1.26.5
    - webencodings==0.5.1
    - websocket-client==1.1.0
    - xlrd==1.2.0
    - yarl==1.6.3
    - zipp==3.4.1

**Comment by lachlangrose** [comment] 2021-06-22 23:27
Hi, 

I've had a look at the environment. I notice when I create this environment I get an error with lavavu

![image](https://user-images.githubusercontent.com/7371904/123011108-28d57400-d403-11eb-971d-32ad95526eb4.png)

I think the issue is that Lavavu hasn't been built using this specific version of python 3.7.1 and there is some c++ dependency conflict causing a dll import error. 

I have found that lavavu 1.8.2 works for python 3.7.1. I can create a LavaVuViewer, so this should get you started.

Let me know if this works and I'll close the issue

**Comment by mustaeenqazi** [comment] 2021-06-23 17:15
Thank you very much for your effort in resolving this issue. The issue got solved with Python 3.7.7 on my local machine with Windows Operating system, Unfortunately I have to run the Framework on GPU cluster at my university which has a Linux ubuntu distribution and there the LAVAVU caused the same error with Python 3.7.7. Ill try this solution and will let you know.
Thanks again,
cheers

**Comment by lachlangrose** [comment] 2021-06-23 23:04
@mustaeenqazi you might have issues using lavavu without a desktop environment, try using lavavu-osmesa instead of lavavu. This package doesn't require any x server so will work on a headless box. 

FYI LoopStructural currently does use the GPU for any computation. If you have any issues/suggestions keep posting.

**Closed** 2021-08-21 22:51 UTC
Labels: bug

**Comment by mustaeenqazi** [comment] 2021-08-24 20:59
Yes i will try lavavu-omesa as well, currently i can atleast save my models and view them using a different package. Thank you very much for your input and help resolving the issue. I appreciate it :)
