### ISSUE TITLE
[BUG] Fold failures

### ISSUE THREAD

**Issue by awickert** [Loop3D/LoopStructural#61] opened 2021-03-16 09:51 UTC
Both of the fold examples return the following error when I run them:

```
AttributeError: 'NoneType' object has no attribute 'fold_limb_rotation'
```

Would it be possible to verify whether this is reproducible? I am using v1.0.89 via pip3.

**Comment by lachlangrose** [comment] 2021-03-16 10:19
I can confirm this is occurring in the most recent version as well - I'll have to look into it, strangely doesn't occur in a notebook example running the same model. Will check it out.

**Comment by lachlangrose** [comment] 2021-03-16 11:05
This should be fixed in 1.0.9, the fold was not being added the the geological feature that was being created when using the create_and_add_folded_foliation method.

**Comment by awickert** [comment] 2021-03-16 11:55
`plot_adding_folds_to_surfaces.py` confirmed to work. Output:
![default](https://user-images.githubusercontent.com/1714966/111305194-9fa0eb00-8624-11eb-992d-3fe7e52f2c0e.png)
![default-00001](https://user-images.githubusercontent.com/1714966/111305195-9fa0eb00-8624-11eb-8eff-1e4ad0240b7b.png)

**Comment by awickert** [comment] 2021-03-16 11:57
`plot_refolded_folds.py`: many WARNINGs but appears to work:

```
andy@cuesta:~/dataanalysis/LoopStructural/examples/2_fold$ python3 plot_refolded_folds.py 
2021-03-16 06:56:00,139 ~ LoopStructural.modelling.features.structural_frame_builder ~ WARNING    ~ Not enough constraints for structural frame coordinate 1, 
Add some more and try again.
2021-03-16 06:56:00,139 ~ LoopStructural.modelling.features.structural_frame_builder ~ WARNING    ~ Not enough constraints for structural frame coordinate 1, 
Add some more and try again.
2021-03-16 06:56:00,139 ~ LoopStructural.modelling.features.structural_frame_builder ~ WARNING    ~ Not enough constraints for fold frame coordinate 1, 
Add some more and try again.
2021-03-16 06:56:00,139 ~ LoopStructural.modelling.features.structural_frame_builder ~ WARNING    ~ Not enough constraints for fold frame coordinate 1, 
Add some more and try again.
2021-03-16 06:56:02,308 ~ LoopStructural.modelling.features.structural_frame_builder ~ WARNING    ~ Not enough constraints for structural frame coordinate 1, 
Add some more and try again.
2021-03-16 06:56:02,308 ~ LoopStructural.modelling.features.structural_frame_builder ~ WARNING    ~ Not enough constraints for structural frame coordinate 1, 
Add some more and try again.
2021-03-16 06:56:02,309 ~ LoopStructural.modelling.features.structural_frame_builder ~ WARNING    ~ Not enough constraints for fold frame coordinate 1, 
Add some more and try again.
2021-03-16 06:56:02,309 ~ LoopStructural.modelling.features.structural_frame_builder ~ WARNING    ~ Not enough constraints for fold frame coordinate 1, 
Add some more and try again.
```

![default](https://user-images.githubusercontent.com/1714966/111305322-c7904e80-8624-11eb-880c-9cae5cb163ec.png)
![default-00001](https://user-images.githubusercontent.com/1714966/111305324-c828e500-8624-11eb-9d4d-d3d1435643bd.png)
![default-00002](https://user-images.githubusercontent.com/1714966/111305326-c828e500-8624-11eb-900b-b5fb68c22c7b.png)
![default-00003](https://user-images.githubusercontent.com/1714966/111305327-c8c17b80-8624-11eb-9171-5bed2561e8c8.png)

**Comment by lachlangrose** [comment] 2021-03-19 03:06
This looks like it is working correctly, the warnings are occurring because coordinates 1 and 2 are not built for the fold frame. In this case where the fold axes are cylindrical, it is not necessary to use all coordinates of the fold frame.

**Closed** 2021-08-21 23:02 UTC
Labels: bug
